name:                pandoc-aozora-ruby
version:             0.1.0.0
github:              "minoki/pandoc-aozora-ruby"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2018 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/pandoc-aozora-ruby#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc-types >= 1.17.2 # pandoc-types 1.17.2 adds 'Walkable [Inline] Pandoc' instance
# - pandoc >= 1.18       # pandoc 1.18 is the minimum version compatible with pandoc-types 1.17.2


library:
  source-dirs: src

executables:
  pandoc-aozora-ruby-filter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-aozora-ruby

tests:
  pandoc-aozora-ruby-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-signatures
    dependencies:
    - pandoc-aozora-ruby
    - pandoc >= 1.18
    - text
    - data-default
    - HUnit
